name: CI/CD
on:
  push:
    branches: [main]
env:
  version: 99.9.${{github.run_number}}
  solutionName: "BcSampleAppsSolution"
  postFix: CICD

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update solution version
        shell: pwsh
        run: |
          .github/actions/script/updateSolutionFile.ps1 -solutionPath ${{env.solutionName}}/Other/Solution.xml -version ${{env.version}} -postFix ${{env.postFix}}

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: "output/${{env.solutionName}}.zip"
          solution-folder: "${{env.solutionName}}"
          solution-type: "Unmanaged"
          process-canvas-apps: true

      - name: Who am I
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{secrets.PowerUser}}
          password-secret: ${{secrets.PowerPassword}}
          environment-url: ${{secrets.PowerEnv}}

      - name: Publish solution to Power Platform
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          user-name: ${{secrets.PowerUser}}
          password-secret: ${{secrets.PowerPassword}}
          environment-url: ${{secrets.PowerEnv}}
          solution-file: output/${{env.solutionName}}.zip
          force-overwrite: true
          publish-changes: true

      - name: Upload solution as artifact store
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.solutionName}}
          path: output/${{env.solutionName}}.zip
