# This is a basic workflow to help you get started with Actions

name: Create release

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Analyze Artifacts
        id: analyzeartifacts
        run: |
          $ErrorActionPreference = "STOP"
          Set-StrictMode -version 2.0
          
          $include = @()
          $sha = ''
          $allArtifacts = @()
          $page = 1
          $headers = @{ 
            "Authorization" = "token ${{ github.token }}"
            "Accept"        = "application/json"
          }
          
          $repoArtifacts = Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri "$($ENV:GITHUB_API_URL)/repos/$($ENV:GITHUB_REPOSITORY)/actions/artifacts?per_page=100&page=$page" | ConvertFrom-Json
          
          Write-Host "Repo Artifacts count: $($repoArtifacts.total_count)"
          Write-Host "Downloaded Artifacts count: $($allArtifacts.Count)"
