name: Deploy solution from branch

on:
  workflow_dispatch:
    inputs:
      environment:
        type: text
        description: The environment to deploy to
        default: QA
        required: true
      version:
        description: Tag of this release (needs to be semantic version string https://semver.org, ex. 1.0.0)
        required: true
        default: "1.1.2"
        type: text
      postFix:
        description: Postfix the solution name with 'dev'
        required: true
        default: true
        type: boolean

env:
  bcPowerAppsName: BcSampleAppsSolution

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Update solution version
        shell: pwsh
        run: |
          script/updateSolutionVersion.ps1 -solutionPath ${{ env.bcPowerAppsName }}/Other/Solution.xml -version ${{ github.event.inputs.version }} -dev "$${{ github.event.inputs.postFix }}"
      
      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: 'output/${{ env.bcPowerAppsName }}.zip'
          solution-folder: '${{ env.bcPowerAppsName }}'
          solution-type: 'Unmanaged'
          process-canvas-apps: true

      - name: Who am I 
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}        
          
      - name: Publish solution to Power Platform
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}
          solution-file: output/${{ env.bcPowerAppsName }}.zip
          force-overwrite: true
          publish-changes: true

      - name: Upload solution as artifact store
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.bcPowerAppsName }}
          path: output/${{ env.bcPowerAppsName }}.zip
