name: Deploy release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: text
        description: The environment to deploy to
        default: QA
        required: true
      version:
        description: Tag corresponding to an available release
        required: true
        default: "1.1.4"

env:
  bcPowerAppsName: BcSampleAppsSolution

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    
    steps:
      - name: Get Release files
        run: echo "NOT IMPLEMENTED YET"

      - name: Who am I 
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}        
          
      - name: Publish solution to Power Platform
        uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}
          solution-file: output/${{ env.bcPowerAppsName }}.zip
          force-overwrite: true
          publish-changes: true

      - name: Upload solution as artifact store
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.bcPowerAppsName }}
          path: output/${{ env.bcPowerAppsName }}.zip
