# This is a basic workflow to help you get started with Actions

name: Deploy solution

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: QA
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: 'output/BcSampleAppSolution.zip'
          solution-folder: 'BcSampleAppSolution'
          solution-type: 'Unmanaged'
          process-canvas-apps: true

      - name: Who am I 
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}
          
          
      - name: Export solution as unmanaged
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{secrets.powerenv}}
          user-name: ${{secrets..PowerUSERNAME}}
          password-secret: ${{ secrets.powerpassword }}
          solution-name: BcSampleAppSolution
          managed: false
          solution-output-file: output/BcSampleAppSolution.zip

      - name: Upload the ready to ship solution to GH artifact store
        uses: actions/upload-artifact@v2
        with:
          name: BcSampleAppSolution
          path: output/BcSampleAppSolution.zip
