name: Test flow2
on:
  workflow_dispatch:
    inputs:
      solutionName:
        description: Name of the Power Platform solution
        required: true
        default: BcSampleAppsSolution
      managed:
        description: Deploy the solution as a managed solution
        required: true
        default: false
        type: boolean

env:
  deployManaged: ${{github.event.inputs.managed == 'true'}}
  packageType: "Unmanaged"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Update solution version
        shell: pwsh
        run: |
          .github/actions/script/updateSolutionFile.ps1 -solutionPath ${{github.event.inputs.solutionName}}/Other/Solution.xml -managed ${{env.deployManaged}}

      - name: Set managed envVariable
        if: github.event.inputs.managed == 'true'
        run: echo "packageType=Managed" >> $GITHUB_ENV

      - name: Pack Unmanged solution
        if: ${{github.event.inputs.managed}}
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: output/${{github.event.inputs.solutionName}}.zip
          solution-folder: ${{github.event.inputs.solutionName}}
          solution-type: ${{env.packageType}}
          process-canvas-apps: true
