name: package-solution

on: [push]

jobs:
  firstJob: 
    name: step1
    runs-on: ubuntu-latest 
    steps:
      - run: echo "No one man should have all that Power!!"
      
      - name: powerplatform-actions
        uses: microsoft/powerplatform-actions@v0.10.1
         
