name: package-solution

on:
  workflow_dispatch:
    inputs:
      solutionPath:
        required: true
        type: text
        default: "BcSampleAppSolution"
      solutionName: 
        required: true
        type: text
        default: "BcSampleAppSolution"
      
permissions:
  actions: write

jobs:
  package-solution: 
    name: Package Solution
    runs-on: ubuntu-latest 
    steps:  
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Update solution version
        shell: pwsh
        run: |
          script/updateSolutionVersion.ps1 -solutionPath ${{ github.event.inputs.solutionPath }}/Other/Solution.xml -version "1.0.1.0"

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: 'output/${{ github.event.inputs.solutionName }}.zip'
          solution-folder: ${{ github.event.inputs.solutionPath }}
          solution-type: 'Unmanaged'
          process-canvas-apps: true
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.event.inputs.solutionName }}
          path: output
