name: package-solution

on: [push]

permissions:
  actions: write

jobs:
  package-solution: 
    name: Package Solution
    runs-on: ubuntu-latest 
    steps:  
      - name: Check out code
        uses: actions/checkout@v2.6.0
        
      - name: Update solution version
        shell: pwsh
        run: |
          script/updateSolutionVersion.ps1 -solutionPath BcSampleAppSolution/Other/Solution.xml -version "1.0.1.0"

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: 'output/BcSampleAppSolution.zip'
          solution-folder: 'BcSampleAppSolution'
          solution-type: 'Unmanaged'
          process-canvas-apps: true
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: BcPowerApps
          path: output
