name: Get latest solution changes

on:
  workflow_dispatch:
    inputs:
      environment:
        type: text
        description: The environment to get latest changes from
        default: QA
env:
  solutionName: BcSampleAppsSolution

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  get-changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{github.event.inputs.environment}}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: who-am-i action
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}

      - name: export-solution action
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          user-name: ${{ secrets.PowerUser }}
          password-secret: ${{ secrets.PowerPassword }}
          environment-url: ${{ secrets.PowerEnv }}
          solution-name: ${{ env.solutionName }}
          solution-output-file: ${{ env.solutionName }}.zip

      - name: unpack-solution action
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ env.solutionName }}.zip
          solution-folder: ${{ env.solutionName }}
          solution-type: 'Unmanaged'
          overwrite-files: true
          
      - name: Git commit
        run:   git config user.email "git@example.com"; git config user.name "Workflow"; git add . ; git commit -m "pull latest solution changes"; 
