name: Test run package flow

on: [workflow_dispatch]

jobs:
  runPackage: 
    runs-on: ubuntu-latest 
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: run action 
        uses: ./.github/actions/package.yaml@main
